=== elpaisa22/ambar/ambar-core/ambar-core-dictionary/src/main/resources/NavigationManager.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:ambar="http://www.ambar.org/navigation"
	targetNamespace="http://www.ambar.org/navigation">
	
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/xml.xsd" />

	<xsd:annotation>
		<xsd:documentation>
		   Formato del documento que especifica la metadata de la navegacion de entidades.
		</xsd:documentation>
	</xsd:annotation>
	
	<xsd:element name="navigationManager">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="entitiesInformation" type="ambar:EntitiesInformation"/>
				<xsd:element name="navigation" type="ambar:Navigation"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="EntitiesInformation">
		<xsd:sequence>
			<xsd:element name="entity" type="ambar:Entity" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Entity">
		<xsd:sequence>
			<xsd:element name="subentity" type="ambar:SubEntity" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string"/>
		<xsd:attribute name="service" type="xsd:string"/>
		<xsd:attribute name="crud" type="xsd:string"/>
		<xsd:attribute name="image-small" type="xsd:string"/>
		<xsd:attribute name="image-big" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="SubEntity">
		<xsd:attribute name="id" type="xsd:string"/>
		<xsd:attribute name="text" type="xsd:string"/>
		<xsd:attribute name="filterCondition" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Navigation">
		<xsd:sequence>
			<xsd:element name="module" type="ambar:Module" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Module">
		<xsd:sequence>
			<xsd:element name="item" type="ambar:Item" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string"/>
		<xsd:attribute name="text" type="xsd:string"/>
		<xsd:attribute name="icon" type="xsd:string"/>
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="entity" type="xsd:string"/>
		<xsd:attribute name="text" type="xsd:string"/>
	</xsd:complexType>

</xsd:schema>

=== elpaisa22/ambar/ambar-core/ambar-core-dictionary/src/test/resources/NavigationManager.xml
<navigationManager xmlns="http://www.ambar.org/navigation"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ambar.org/navigation NavigationManager.xsd">

	<entitiesInformation>
		<entity id="Cliente" image-big="assets/icons/user.png"
			image-small="assets/icons/user.png" service="IClienteService" crud="ABMCliente">
			<subentity id="Venta" text="Ventas" filterCondition="VENTAS.IdCliente = :idCliente" />
		</entity>
		<entity id="Venta" image-big="assets/icons/page.png"
			image-small="assets/icons/page.png" service="IVentaService" crud="ABMVenta">
			<subentity id="Pago" text="Mis Pagos" filterCondition="PAGO.idVenta = :idVenta" />
			<subentity id="Deuda" text="Mis Deudas" filterCondition="DEUDA.idVenta = :idVenta" />
		</entity>
		<entity id="Pago" image-big="assets/icons/bell.png"
			image-small="assets/icons/bell.png" service="IVentaService" crud="ABMVenta" />
		<entity id="Deuda" image-big="assets/icons/money.png"
			image-small="assets/icons/money.png" service="IVentaService" crud="ABMVenta" />
	</entitiesInformation>

	<navigation>
		<module id="Principal" text="Modulo de Clientes" icon="assets/icons/user.png">
			<item entity="Cliente" text="Mis Clientes" />
			<item entity="Venta" text="Mis Ventas" />
		</module>
	</navigation>
</navigationManager>
